name: 'Hello World'
description: 'Greet someone'
outputs:
  name:
    description: "Random name"
    value: ${{ steps.random-name-provider.outputs.random-name }}
runs:
  using: "composite"
  steps:
    - id: random-name-provider
      run: echo "random-name=batman" >> $GITHUB_OUTPUT
      shell: bash
