name: 'Hello World'
description: 'Greet someone'

outputs:
  name:
    description: "Random number"
    value: ${{ steps.provide-name.outputs.random-name }}
runs:
  using: "composite"
  steps:

    - id: provide-name
      run: echo "random-name=batman" >> $GITHUB_OUTPUT
      shell: bash
