name: "Say Hello"

outputs:
  name:
    description: "A name"
    value: steve
    #value: ${{ steps.provide-name.outputs.random-name }}

runs:
  using: "composite"
  steps:
    - run: echo "hello there"
    
    #- id: provide-name
    #  run: echo "random-name=batman" >> $GITHUB_OUTPUT
