name: dispatch_with_inputs

on: 
  workflow_dispatch:
    inputs:
      username:
        required: true
        type: string
      department:
        required: true
        type: string
      
jobs:
  display_username:
    runs-on: ubuntu-latest
    steps:
      - name: echo username
        run: echo ${{ inputs.username }}
        
      - name: echo department
        run: echo ${{ inputs.department }}
